#!/tmp/busybox sh
rm /system/app/DeskClock.apk
rm /system/app/FactoryTest.apk
rm /system/app/install_flash_player.apk
rm /system/app/LiveWallpapers.apk
rm /system/app/LiveWallpapersPicker.apk
rm /system/app/MusicPlayer.apk
rm /system/app/PicoTts.apk
rm /system/app/RoseEUKor.apk
rm /system/app/serviceModeApp.apk
rm /system/app/Street.apk
rm /system/app/TouchWizCalculator.apk
rm /system/app/TouchWizCalendar.apk
rm /system/app/Calculator.apk
rm /system/app/Calendar.apk
rm /system/app/TtsService.apk
rm /system/app/TwWallpaperChooser.apk
rm /system/app/UserDictionaryProvider.apk
rm /system/app/VoiceDialer.apk
rm /system/app/VoiceRecorder.apk
## apps samsung
rm  /system/app/BuddiesNow.apk
rm  /system/app/aldiko-standard-1.2.6.1-samsung-s1.apk
rm  /system/app/ChocoEUKor.apk
rm  /system/app/CoolEUKor.apk
rm  /system/app/Days.apk
rm  /system/app/DualClock.apk
rm  /system/app/Layar-samsung.apk
rm  /system/app/Memo.apk
rm  /system/app/MiniDiary.apk
rm  /system/app/PressReader.apk
rm  /system/app/RoseEUKor.apk
rm  /system/app/SamsungApps.apk
rm  /system/app/SamsungWidget_CalendarClock.apk
rm  /system/app/SamsungWidget_FeedAndUpdate.apk
rm  /system/app/SamsungWidget_ProgramMonitor.apk
rm  /system/app/SamsungWidget_StockClock.apk
rm  /system/app/WriteandGo.apk
rm  /system/app/VoiceSearch.apk
rm  /system/app/UnifiedInbox.apk
rm  /system/app/talkback.apk
