#!/system/bin/sh

#vurrutROM tweaks

#cpu
echo "120000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "1200000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "smartassV2" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

#scheduler deadline

  for i in $(ls -1 /sys/block/stl*) $(ls -1 /sys/block/mmc*)
  do 
    echo "deadline" > $i/queue/scheduler
    echo "8" > $i/queue/iosched/fifo_batch
    echo "16" > $i/queue/iosched/quantum
    echo "400" > $i/queue/iosched/read_expire
    echo "4" > $i/queue/iosched/writes_starved

  done
fi;
#smartassV2 settings for balanced mode
echo "500000" > /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq;
echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;
echo "500000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_wakeup_freq
echo "85" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load;
echo "70" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load;
echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step;
echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step;
echo "48000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us
echo "49000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us

