#!/system/bin/sh

#vurrutROM tweaks

#cpu
echo "120000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "1000000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "smartassV2" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

#scheduler vr

  for i in $(ls -1 /sys/block/stl*) $(ls -1 /sys/block/mmc*)
  do 
    echo "vr" > $i/queue/scheduler
  done
fi;

#Smartass v2 settings for performace mode.

echo "800000" > /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq;
echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;
echo "800000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_wakeup_freq
echo "75" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load;
echo "45" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load;
echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step;
echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step;
echo "24000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us
echo "99000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us

