#!/system/bin/sh

#vurrutROM tweaks

#cpu
echo "120000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "1000000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

#scheduler cfq

  for i in $(ls -1 /sys/block/stl*) $(ls -1 /sys/block/mmc*)
  do 
    echo "cfq" > $i/queue/scheduler
  done
fi;

#Conservative settings for saver mode.

echo "95" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
echo "120000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate
echo "1" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
echo "40" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
echo "10" > /sys/devices/system/cpu/cpufreq/conservative/freq_step



